import "../globals.css";
import type { Metadata } from "next";
import { inter, prompt } from "../fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${inter.className}, ${prompt.variable}`}>
      <body>{children}</body>
    </html>
  );
}
