import { AppLayout } from "@/components/AppLayout";
import "./globals.css";
import type { Metadata } from "next";
import { cookies } from "next/headers";
import { inter, prompt } from "./fonts";
import { createServerComponentClient } from "@supabase/auth-helpers-nextjs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Adding force-dynamic was necessitated by the use of cookies for Supabase,
 * which are themselves required for Supabase Auth. If the following issue:
 * https://github.com/vercel/next.js/issues/49373 is resolved, this line
 * may be removable.
 */
export const dynamic = "force-dynamic";

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const supabase = createServerComponentClient({ cookies });

  const {
    data: { user },
  } = await supabase.auth.getUser();

  return (
    <html lang="en" className={`${inter.className}, ${prompt.variable}`}>
      <body>
        <AppLayout user={user}>{children}</AppLayout>
      </body>
    </html>
  );
}
